"""
Structure-agnostic source segmentation.

build_blocks      -> lossless atomic paragraph blocks (never cut inside a fenced
                     code block, Markdown table run, or <image-unit> block).
embed_blocks      -> one vector per block via the shared Embedder.
segment_source    -> hybrid A+B segmentation returning wiki_new ConceptFilePlan
                     objects with exact, contiguous 1..N line coverage.

Method A: cosine distance between consecutive block embeddings; the top
(100 - SEM_PERCENTILE)% gaps are candidate boundaries.
Method B: at each size-eligible candidate, the LLM confirms (yes/no) whether a
new section actually starts. No partition is ever generated by the model.
"""

from __future__ import annotations

import asyncio
import math
import re

from langchain_core.messages import HumanMessage, SystemMessage

from wiki_embed.models import (
    EMBED_BATCH,
    EMBED_CONCURRENCY,
    MAX_LINES,
    REFINE_BACK_LINES,
    REFINE_CONCURRENCY,
    REFINE_FWD_LINES,
    SEM_PERCENTILE,
    TARGET_LINES,
    USE_LLM_CONFIRM,
    BoundaryDecision,
)
from wiki_new.llm import structured_ainvoke
from wiki_new.planning import ConceptFilePlan, validate_safe_internal_boundary
from wiki_new.utils import (
    is_fence_line,
    is_tableish_line,
    numbered_source_lines,
    slugify,
)

_DATA_IMAGE_URI_RE = re.compile(
    r"data:image/[a-zA-Z0-9.+-]+;base64,[A-Za-z0-9+/=\r\n]+",
    re.IGNORECASE,
)
_HEADING_RE = re.compile(r"^\s{0,3}#{1,6}\s+(.+?)\s*#*\s*$")
# Headings/lines that close a section and belong with the section before them;
# never use them as a page title or as the start of a new page.
_CLOSING_RE = re.compile(
    r"^\s*(summary|conclusions?|references|acknowledg(e?ments?)?|exercises|"
    r"further reading|key takeaways|bibliography|index|notes|appendix)\b",
    re.IGNORECASE,
)


# ---------------------------------------------------------------------
# Block building (lossless atomic units)
# ---------------------------------------------------------------------


def build_blocks(source_lines: list[str]) -> list[tuple[int, int]]:
    """
    Split source into contiguous blocks (0-based inclusive index pairs).

    A block ends at a blank line, except blank lines inside a fenced code block
    or an <image-unit> block do not terminate it. Trailing blank lines are kept
    with the block that precedes them, so coverage is exact and gap-free.
    """

    n = len(source_lines)
    blocks: list[tuple[int, int]] = []
    i = 0

    while i < n:
        start = i
        in_fence = False
        in_image = False
        j = i

        while j < n:
            line = source_lines[j]

            if is_fence_line(line):
                in_fence = not in_fence
            if "<image-unit>" in line:
                in_image = True
            if "</image-unit>" in line:
                in_image = False

            if not in_fence and not in_image and line.strip() == "":
                # Absorb a run of blank lines into this block, then stop.
                while j + 1 < n and source_lines[j + 1].strip() == "":
                    j += 1
                break

            j += 1

        end = min(j, n - 1)
        blocks.append((start, end))
        i = end + 1

    return blocks


def _clean_for_embed(text: str) -> str:
    text = _DATA_IMAGE_URI_RE.sub("data:image;base64,[omitted]", text)
    return text.strip() or " "


def _block_text(source_lines: list[str], block: tuple[int, int]) -> str:
    start, end = block
    return _clean_for_embed("\n".join(source_lines[start : end + 1]))


# ---------------------------------------------------------------------
# Embedding + semantic distance
# ---------------------------------------------------------------------


async def embed_blocks(embedder, texts: list[str]) -> list[list[float]] | None:
    """Embed every block, batches running concurrently (EMBED_CONCURRENCY in
    flight). Returns None if the backend fails (size-only fallback)."""
    total = len(texts)
    batches = [texts[i : i + EMBED_BATCH] for i in range(0, total, EMBED_BATCH)]
    semaphore = asyncio.Semaphore(EMBED_CONCURRENCY)
    done = 0

    async def run_batch(batch: list[str]) -> list[list[float]]:
        nonlocal done
        async with semaphore:
            part = await asyncio.to_thread(embedder.embed_documents, batch)
        done += len(batch)
        print(f"    embedded {done}/{total} blocks")
        return part

    try:
        # gather preserves order, so the flattened vectors stay aligned to texts.
        results = await asyncio.gather(*(run_batch(b) for b in batches))
    except Exception as exc:  # noqa: BLE001 - fall back to size-only chunking
        print(f"[Embed] failed ({exc}); falling back to size-only segmentation.")
        return None

    vectors: list[list[float]] = []
    for part in results:
        vectors.extend(part)
    return vectors


def _cosine_distance(a: list[float], b: list[float]) -> float:
    dot = sum(x * y for x, y in zip(a, b))
    na = math.sqrt(sum(x * x for x in a))
    nb = math.sqrt(sum(y * y for y in b))
    if na == 0.0 or nb == 0.0:
        return 0.0
    return 1.0 - (dot / (na * nb))


def _percentile(values: list[float], pct: float) -> float:
    if not values:
        return 0.0
    ordered = sorted(values)
    k = (len(ordered) - 1) * pct / 100.0
    lo = math.floor(k)
    hi = math.ceil(k)
    if lo == hi:
        return ordered[int(k)]
    return ordered[lo] * (hi - k) + ordered[hi] * (k - lo)


# ---------------------------------------------------------------------
# Method B: single-boundary confirmation
# ---------------------------------------------------------------------


def _build_refine_prompt(
    *,
    source_lines: list[str],
    dip_line: int,
    window_lo: int,
    window_hi: int,
) -> list:
    window = numbered_source_lines(
        source_lines[window_lo - 1 : window_hi],
        window_lo,
    )

    return [
        SystemMessage(
            content=(
                "You place ONE exact section boundary in a document. A semantic "
                "shift was detected near a line; choose the exact line where the "
                "NEXT reader-facing section truly begins. Work from the text "
                "itself (topic shifts, new chapter/section starts) — the document "
                "may have no markdown headings at all. A boundary will be placed "
                "here regardless; your job is only to choose the best line. "
                "Return structured output only."
            )
        ),
        HumanMessage(
            content=(
                f"A semantic shift was detected near source line {dip_line}.\n"
                f"Set the boundary at any line from {window_lo} to {window_hi} "
                "(inclusive), using the line numbers shown.\n\n"
                "Rules:\n"
                "- 'boundary_line' = the first line of the NEW section.\n"
                "- A trailing summary, conclusion, recap, references, or "
                "acknowledgements belongs to the section ABOVE it. Do NOT start "
                "a new section at such closing material — move the boundary down "
                "to the line where the genuinely new topic/chapter starts.\n"
                "- Never start a new section in the middle of a sentence, list, "
                "table, or code block.\n"
                "- Pick the strongest, most natural reader-facing break.\n\n"
                "Numbered source lines around the dip:\n"
                f"{window}"
            )
        ),
    ]


async def _refine_boundary(
    *,
    llm,
    source_lines: list[str],
    dip_line: int,
    lower_bound: int,
    upper_bound: int,
) -> int:
    """Return the exact 1-based start-of-next-section line near dip_line.

    The result is always a real cut, constrained to (lower_bound, upper_bound].
    Falls back to dip_line when the model output is unusable.
    """

    n = len(source_lines)
    window_lo = max(lower_bound + 1, dip_line - REFINE_BACK_LINES)
    window_hi = min(n, upper_bound, dip_line + REFINE_FWD_LINES)
    fallback = min(max(dip_line, window_lo + 1), window_hi)

    if window_lo >= window_hi:
        return fallback

    messages = _build_refine_prompt(
        source_lines=source_lines,
        dip_line=dip_line,
        window_lo=window_lo,
        window_hi=window_hi,
    )

    try:
        raw = await structured_ainvoke(
            llm,
            BoundaryDecision,
            messages,
            max_output_tokens=160,
            phase="wiki_embed.boundary_refine",
            enable_thinking=False,
        )
        decision = BoundaryDecision.model_validate(raw)
    except Exception as exc:  # noqa: BLE001
        print(f"[Refine] dip {dip_line}: error ({exc}); using fallback.")
        return fallback

    line = decision.boundary_line
    if line is None or not (window_lo < line <= window_hi):
        return fallback
    if validate_safe_internal_boundary(source_lines=source_lines, split_line=line):
        # Cut would land inside a fence/table/image block.
        return fallback

    return line


# ---------------------------------------------------------------------
# Title derivation
# ---------------------------------------------------------------------


def _derive_title(source_lines: list[str], src_start: int, src_end: int) -> str:
    span = source_lines[src_start - 1 : src_end]

    # Prefer the first real markdown heading that is not a closing section.
    for line in span:
        match = _HEADING_RE.match(line)
        if match:
            text = match.group(1).strip()
            if text and not _CLOSING_RE.match(text):
                return text[:80]

    # No headings (common in OCR'd / headingless markdown): first substantive,
    # non-closing line.
    for line in span:
        stripped = line.strip().lstrip("#").strip()
        if stripped and not _CLOSING_RE.match(stripped):
            return stripped[:80]

    return f"Section {src_start}"


# ---------------------------------------------------------------------
# Hybrid segmentation
# ---------------------------------------------------------------------


async def segment_source(
    *,
    llm,
    embedder,
    source_lines: list[str],
    tag: str = "",
) -> list[ConceptFilePlan]:
    label = f"[{tag}] " if tag else ""
    if not source_lines:
        return []

    blocks = build_blocks(source_lines)
    print(f"{label}built {len(blocks)} paragraph blocks")

    texts = [_block_text(source_lines, block) for block in blocks]
    print(f"{label}embedding {len(texts)} blocks...")
    embeddings = await embed_blocks(embedder, texts)
    print(f"{label}embedding done")

    # Distance after block i (between block i and i+1). len == len(blocks) - 1.
    if embeddings is not None and len(embeddings) == len(blocks):
        distances = [
            _cosine_distance(embeddings[i], embeddings[i + 1])
            for i in range(len(blocks) - 1)
        ]
        threshold = _percentile(distances, SEM_PERCENTILE)
        semantic = True
    else:
        distances = []
        threshold = 0.0
        semantic = False

    print(
        f"{label}{len(blocks)} blocks, semantic={semantic}, "
        f"distance_threshold={threshold:.4f}"
    )
    n = len(source_lines)

    # Block-gap candidates: gap after block i starts the next block at this line.
    gap_lines = [blocks[i][1] + 2 for i in range(len(blocks) - 1)]
    gap_dist = distances if semantic else []

    def _pick_dip(lo: int, hi: int) -> int:
        """Best cut line in [lo, hi]: strongest semantic dip, else a block
        boundary near hi, else hi itself (hard cut)."""
        in_range = (
            [
                (gap_dist[i], gap_lines[i])
                for i in range(len(gap_lines))
                if lo <= gap_lines[i] <= hi
            ]
            if semantic
            else []
        )
        if in_range:
            return max(in_range)[1]
        block_bnds = [ln for ln in gap_lines if lo <= ln <= hi]
        if block_bnds:
            return block_bnds[-1]
        return hi

    # --- Anchor pass (deterministic, instant): each section is TARGET..MAX, cut
    # at the strongest semantic break in that window. ---
    print(f"{label}segmenting greedily (target={TARGET_LINES} max={MAX_LINES})...")
    anchors: list[int] = []
    last = 1
    while n - last + 1 > MAX_LINES:
        lo = min(last + TARGET_LINES, n)
        hi = min(last + MAX_LINES, n)
        dip_line = _pick_dip(lo, hi)
        if dip_line <= last:  # safety: never stall
            dip_line = hi
        anchors.append(dip_line)
        last = dip_line

    print(f"{label}{len(anchors)} anchors; refining exact cut lines in parallel...")

    # --- Refine pass (parallel): anchors are spaced >= TARGET apart and each
    # refine window is small (REFINE_BACK/FWD), so refined lines cannot cross a
    # neighbour. Each refine is bounded by its neighbour anchors and runs
    # independently. ---
    if USE_LLM_CONFIRM and anchors:
        semaphore = asyncio.Semaphore(REFINE_CONCURRENCY)

        async def refine_anchor(k: int, dip_line: int) -> int:
            prev_anchor = anchors[k - 1] if k > 0 else 1
            next_anchor = anchors[k + 1] if k + 1 < len(anchors) else n + 1
            async with semaphore:
                return await _refine_boundary(
                    llm=llm,
                    source_lines=source_lines,
                    dip_line=dip_line,
                    lower_bound=prev_anchor,
                    upper_bound=next_anchor - 1,
                )

        refined = await asyncio.gather(
            *(refine_anchor(k, dip) for k, dip in enumerate(anchors))
        )
        moved = sum(1 for a, r in zip(anchors, refined) if a != r)
        print(f"{label}refine: {len(anchors)} anchors, {moved} moved")
    else:
        refined = anchors

    # Enforce strictly increasing boundaries (guard against any rare crossing).
    boundary_lines: list[int] = []
    prev = 1
    for line in sorted(refined):
        if line > prev:
            boundary_lines.append(line)
            prev = line

    # --- Build contiguous sections from accepted boundary lines ---
    bounds = [1] + boundary_lines + [n + 1]
    plans: list[ConceptFilePlan] = []
    for k in range(len(bounds) - 1):
        src_start = bounds[k]
        src_end = bounds[k + 1] - 1
        if src_end < src_start:
            continue
        title = _derive_title(source_lines, src_start, src_end)
        plans.append(
            ConceptFilePlan(
                title=title,
                filename=f"{slugify(title)}.md",
                source_start=src_start,
                source_end=src_end,
                summary="",
            )
        )

    print(f"{label}produced {len(plans)} section(s).")
    return plans
